### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by rslruiz** [PercivalIII/py3AquamanProject#1]
Update your README.md stating the name of your project, a short description and a list of features.

**Comment by NixLon24** [comment]
Updated the README.md accordingly with the name of the project, a short description and the list of features.
https://github.com/PercivalIII/py3AquamanProject/commit/140d4abeafe49d4ab0d2399a3168573ad42246d9
https://github.com/PercivalIII/py3AquamanProject/commit/a2d50abe628b295e6e79cce021a1d6202da86786
